[project]
name = "forehead"
default_license = "Apache-2.0 OR MIT"
default_author = "Afsall Inc"
default_year = 2026
repository = "https://github.com/afsall-inc/forehead"
description = "A tool for creating and maintaining file headers for code license"

[templates]
mit-apache = "docs/LICENSES/headers/HEADER-MIT-APACHE"

[[mapping]]
paths = ["."]
template = "mit-apache"

[header]
indicators = []
greetings = "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم"